### ISSUE TITLE
ktk crash after tailing for a few seconds

### ISSUE THREAD

**Issue by gilinachum** [blinsay/ktk#2]
I ran on my osx laptop: 
`export AWS_REGION=us-east-1`
`ktk tail my-stream-name`

And got this after a few seconds:
```
panic: InvalidSignatureException: Signature expired: 19700101T000014Z is now earlier than 20161113T191918Z (20161113T192418Z - 5 min.)
	status code: 400, request id: db8800d6-4da4-9d2c-8b2a-c0f4f29c0178

goroutine 10 [running]:
github.com/blinsay/ktk/consumer.(*shardConsumer).consume(0xc820014960)
	/Users/benl/work/src/github.com/blinsay/ktk/consumer/consumer.go:189 +0x380
github.com/blinsay/ktk/consumer.(*Consumer).startShardConsumer.func1(0xc820014960, 0xc820011440)
	/Users/benl/work/src/github.com/blinsay/ktk/consumer/consumer.go:94 +0x39
created by github.com/blinsay/ktk/consumer.(*Consumer).startShardConsumer
	/Users/benl/work/src/github.com/blinsay/ktk/consumer/consumer.go:95 +0x1a9

goroutine 1 [chan receive]:
main.doTail(0xc82000a2f0, 0x1, 0x1)
	/Users/benl/work/src/github.com/blinsay/ktk/tail.go:41 +0x248
main.main()
	/Users/benl/work/src/github.com/blinsay/ktk/ktk.go:99 +0x4e3
...
```

**Comment by blinsay** [comment]
this looks like the request to Kinesis can't be authorized because the request has a strange timestamp. can you check on your OS clock and make sure everything there looks sane?

**Comment by blinsay** [comment]
@gilinachum it turns out that Go 1.6 and earlier don't work correctly on macOS Sierra. Check out [the releases page](https://github.com/blinsay/ktk/releases) for a new version or try upgrading your local Go installation.

feel free to re-open the issue if that doesn't fix your problem!

**Comment by gilinachum** [comment]
@blinsay Hi Ben, I'm using latest GO 1.7.3
```
>go version
go version go1.7.3 darwin/amd64
```

Anyway, I'm currently successfully using [this minimalistic implementation](https://github.com/russellcardullo/kinesis-tail). It worked right of the bat.

I just wish I had an option to tail from a specific datetime, instead of from latest.
